name: debates

services:
  minio-instance:
    image: minio/minio
    volumes:
      - ${MINIO_PATH}:/data
    ports:
      - 127.0.0.1:9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --address 0.0.0.0:9000 --console-address :9001 /data
    networks:
      - debates_network

  solr:
    build:
      context: ./components/solr
    ports:
      - 8983:8983
    networks:
      - debates_network
    healthcheck:
      test: curl --max-time 10 -f http://localhost:8983 || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - ${SOLR_PATH}:/var/solr
    command:
      - solr-precreate
      - debates
      - /opt/solr/server/solr/configsets/debates

  mongodb-instance:
    image: mongo:7.0.8
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: debates
    networks:
      - debates_network
    volumes:
      - ${MONGO_PATH}:/data/db

  mongodb-express:
    image: mongo-express:1.0.2-18
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-instance:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    networks:
      - debates_network
    depends_on:
      - mongodb-instance

  dataloader:
      build:
        context: ./components/dataloader
        dockerfile: Dockerfile
      networks:
        - debates_network
      environment:
        SOLR_URL: http://solr:8983/solr/debates/
        MONGO_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-instance:27017/
        MONGO_DB: debates
        S3_SERVER: http://minio-instance:9000
        S3_FRONTEND_BASE_URL: http://localhost:80
        S3_ACCESS_KEY: ${S3_ACCESS_KEY}
        S3_SECRET_KEY: ${S3_SECRET_KEY}
        API_HOST: "0.0.0.0"
      ports:
        - 8000:8000
      depends_on:
        - minio-instance
        - mongodb-instance
        - solr

  whisper-diarize:
    image: registry.hf.space/katospiegel-odtp-pyannote-whisper:latest
    platform: linux/amd64
    ports:
      - "7860:7860" # This will be available at http://localhost:7860
    environment:
      - ODTP_API_MODE=TRUE
      - HF_TOKEN=${HF_TOKEN}
    networks:
      - debates_network
    # You might also need these, which are the equivalent of '-it'
    stdin_open: true
    tty: true

networks:
  debates_network:
    driver: bridge
