[project]
name = "debates-backend"
version = "0.1.0"
requires-python = ">= 3.11"

dependencies = [
    "typer>=0.12.5",
    "python-dotenv>=1.0.1",
    "pymongo>=4.10.1",
    "requests>=2.32.3",
    "pysolr>=3.10.0",
    "boto3>=1.35.49",
    "fastapi[standard]>=0.115.4",
    "rq>=2.6.1",
]
