services:
  solr:
    build:
      context: ../../components/solr
    ports:
      - 8983:8983
    networks:
      - debates_network
    container_name: solr
    labels:
      - "dev.dozzle.name=Solr"
      - "dev.dozzle.group=Services"
    healthcheck:
      test: curl --max-time 10 -f http://localhost:8983 || exit 1
      start_period: 60s
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - solr:/var/solr
    command:
      - solr-precreate
      - debates
      - /opt/solr/server/solr/configsets/debates

  mongodb-instance:
    image: mongo:7.0.8
    ports:
      - 127.0.0.1:27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: debates
    container_name: mongo-db
    labels:
      - "dev.dozzle.name=Mongo DB"
      - "dev.dozzle.group=Services"
    networks:
      - debates_network
    volumes:
      - mongo:/data/db
    healthcheck:
      # We use $$ to tell Docker Compose "don't replace this, let the container shell handle it"
      test:
        [
          "CMD-SHELL",
          'mongosh --username $$MONGO_INITDB_ROOT_USERNAME --password $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --quiet --eval "db.adminCommand(''ping'').ok"',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mongodb-express:
    image: mongo-express:1.0.2-18
    ports:
      - 127.0.0.1:8081:8081
    container_name: mongo-express
    labels:
      - "dev.dozzle.name=Mongo Express"
      - "dev.dozzle.group=Services"
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-instance:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
    networks:
      - debates_network
    depends_on:
      - mongodb-instance

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - debates_network
    container_name: redis
    labels:
      - "dev.dozzle.name=Redis"
      - "dev.dozzle.group=Services"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  garage:
    build:
      context: ../../components/garage
    container_name: garage
    restart: unless-stopped
    labels:
      - "dev.dozzle.name=Garage"
      - "dev.dozzle.group=Services"
    ports:
      - "3900:3900"
    volumes:
      - garage:/var/lib/garage
    environment:
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
    networks:
      - debates_network
