[project]
name = "workers-services"
version = "0.1.0"
requires-python = ">= 3.11"

dependencies = [
    "boto3>=1.35.49",
    "rq>=2.6.1",
    "redis",
    "gradio-client>=2.0.0",
    "pymongo>=4.15.4",
    "srt>=3.5.3",
    "pydantic-settings>=2.12.0",
    "pydantic>=2.12.5",
]
