site_name: Political Debates
site_url: https://github.com/sdsc-ordes
repo_url: https://github.com/sdsc-ordes/debates-analytics
repo_name: sdsc-ordes/debates-analytics
docs_dir: docs
use_directory_urls: false
plugins:
  - search
  - link-marker
  - swagger-ui-tag

theme:
  name: material
  logo: static/logo/political_debates_logo.png
  features:
    - navigation.instant
    - content.tooltips
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: orange

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption:
      prepend: false
      auto: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 - 2024 SDSC

# Page tree
nav:
  - Home: index.md
  - User Guide:
      - Roles: userguide/roles.md
      - Dashboard: userguide/dashboard.md
      - Search Page: userguide/searchpage.md
      - Media Player: userguide/mediaplayer.md
      - Advanced CLI: userguide/commandline.md
  - Architecture:
      - Overview: architecture/overview.md
      - Datastorage: architecture/datastorage.md
      - Application: architecture/application.md
      - Processing: architecture/processing.md
      - Upload/Download: architecture/presigned-urls.md
      - WhisperX: architecture/whisperx.md
  - API:
      - openapi: api/openapi.md
  - Installation:
      - Options: installation/overview.md
      - Core Setup: installation/core.md
      - Server Setup: installation/server.md
  - Development:
      - Guidelines: development/setup.md
      - Contributing: development/contributing.md
      - Code of Conduct: development/code-of-conduct.md
  - License: LICENSE.md
