site_name: Political Debates
site_url: https://github.com/sdsc-ordes
repo_url: https://github.com/sdsc-ordes/debates-analytics
repo_name: sdsc-ordes/debates-analytics
docs_dir: docs
use_directory_urls: false
plugins:
  - search
  - link-marker
  - swagger-ui-tag

theme:
  name: material
  logo: static/logo/political_debates_logo.png
  features:
    - navigation.instant
    - content.tooltips
  palette:
    - scheme: default
      primary: indigo
      accent: orange

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.blocks.caption:
      prepend: false
      auto: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

copyright: |
  &copy; 2023 - 2024 SDSC

# Page tree
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Processing Pipeline: processing.md
  - Dataloader: dataloader.md
  - UI:
      - Ingest: ui/ingest.md
  - API: api/api.md
  - Installation:
      - Options: install/options.md
      - Docker Compose Setup: install/compose.md
      - Server Setup: install/server.md
      - Development: install/development.md
  - PoC Status: status.md
