[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-link-marker>=0.1.3",
    "mkdocs-material>=9.6.4",
    "pymdown-extensions>=10.14.3",
    "mkdocs-swagger-ui-tag>=0.7.2",
]
